CREATE TABLE delivery_autenticacao (
  id UNIQUEIDENTIFIER DEFAULT NEWID(),
  nome VARCHAR(128) NOT NULL,
  documento VARCHAR(32) NOT NULL,
  criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT pk_delivery_autenticacao PRIMARY KEY (id)
);
